### ISSUE TITLE
Chat bug when ignored dialog open

### ISSUE THREAD

**Issue by ethanmoffat** [ethanmoffat/EndlessClient#11]
When a dialog is set to 'Ignored' (such is the case for EOPaperdollDialog and EOChestDialog) and is the top-most dialog, typing text in the main chat text box works ok. However, hitting enter or backspace does not work as expected (nothing happens). Suspect this is because these keypresses are being absorbed by the dialog and not passed to the text box, which is updated after the enter keypress is absorbed.

Need to find a way to pass the enter keypress event back to windows if it isn't handled by the dialog. This may be entirely within XNAControls and not require changes in EndlessClient.

**Comment by dgadelha** [comment]
Saw this today.

**Comment by ethanmoffat** [comment]
Fixed with commit 250b9fa (required changes to XNAControls)
