### ISSUE TITLE
opposite gender armor

### ISSUE THREAD

**Issue by Septharoth** [ethanmoffat/EndlessClient#12]
if you try to equip an opposite gender's armor the gfx id loads for that gender's gear but doesn't equip the item

Here's a puush.

http://puu.sh/hr9dx/c73f25154f.jpg It even registers while wearing armor already

**Comment by ethanmoffat** [comment]
Looks like there is no check in place client-side for the item gender before equipping.

**Comment by Septharoth** [comment]
Yeah, I spotted that like 20 minutes after posting this, I ran into a crash bug with NPCs as well, will post it as soon as I figure out what's causing it.

**Comment by ethanmoffat** [comment]
Fixed in commit 2fbfda9.
