### ISSUE TITLE
Character name label can stick around after logging out

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#155]
If the logout "OK!" button is over top of a character and you trigger their name label to appear before clicking it the name label will persist on the main menu screen.

Disappears after selecting a character.

![EndlessClient_Nb1FBe2Pv6](https://user-images.githubusercontent.com/3664832/160276862-c3890657-d69d-43b3-871b-7ef827a62b26.gif)

**Comment by ethanmoffat** [comment]
Known issue (that I hadn't filed yet :) ) - this happens with NPCs as well
