### ISSUE TITLE
Players/NPCs on the edge of the screen get stuck on reoserv/GameServer

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#157]
I'm not exactly sure what triggers it in the official client but it seems like if something is on the very edge of the screen (12 tiles away) it will be dropped from view when the map re-renders.

I wasn't sure where the best place to implement this behavior was though. Up for suggestions if you have any.

__Originally posted by @sorokya in https://github.com/ethanmoffat/EndlessClient/issues/154#issuecomment-1081003320__

**Comment by sorokya** [comment]
> I recently reworked animations pretty heavily. They're *mostly* fixed but still have some work left to do on them - other players walking around will sometimes jump coordinates suddenly or be in the wrong position (requiring an F12).
> 
> 
> 
> I think I've noticed this behavior, when someone is walking off the screen I've noticed them suddenly disappear before they are fully out of view.

I saw the jumping around happen too I think this is a separate issue though.

The original client will drop players/npcs from memory when they're on the other edge of the screen and the map renders.

GameServer/reoserv depends on this because it doesn't send avatar/remove packets and the equivalent for npcs when they go out of view.

The behavior right now with GameServer and reoserv is when a player or npc walks out of range and you walk towards them their ghost will still be there until you F12.

I think the fix would be something like on map render just remove any players or npcs that are 12 or more tiles away from the player

**Comment by ethanmoffat** [comment]
Moving to version 1 milestone, v0.10 is intended to work with eoserv

**Comment by sorokya** [comment]
This will probably be useful
![image](https://user-images.githubusercontent.com/3664832/204926985-c27d3718-9537-4b8f-805c-2a48f57b258c.png)
