### ISSUE TITLE
Friends List [Glitch?]

### ISSUE THREAD

**Issue by JimmysNetwork** [ethanmoffat/EndlessClient#17]
Hello,

I noticed that when you try to spam (right click) remove friends, it will then glitch out the friends list. It seems that it fixes itself, but maybe add a check to prevent removing multiple friends quickly? I haven't peeked at the code much because I'm installing VS atm. I figured I would let you know anyways. I'll post more as I find issues.

Screenshot: http://puu.sh/huQrP/adaae83b4e.jpg

**Comment by Septharoth** [comment]
I spy a little glitch with chat appearing over HUD as well ;)

**Comment by ethanmoffat** [comment]
Fixed in commit f1d3e28
