### ISSUE TITLE
Friends List Glitch #2

### ISSUE THREAD

**Issue by JimmysNetwork** [ethanmoffat/EndlessClient#18]
Currently you can add multiple friends with the same name. For example, you can add lets say "Jimmy" as many times as you like (1, 5, 10000000), but once you 'close/re open' the list, it only shows the first original addition. I wouldn't say this is an important thing to be fixed, but nonetheless less glitchy is better :P 

Screenshot: http://puu.sh/huQT4/2b542fe21b.jpg

**Comment by ethanmoffat** [comment]
Also fixed in commit f1d3e28
