### ISSUE TITLE
HUD Glitch

### ISSUE THREAD

**Issue by JimmysNetwork** [ethanmoffat/EndlessClient#19]
Hi,

1. Currently chat bubbles will overlay the HUD, etc. I don't think I need to provide a screenshot for this glitch, it's very apparent in game. 

2. If you have two items next to each other, the item you're hovering will not show the name properly, as it will be stuck under the other item. (Screenshot: http://puu.sh/huRaO/27ca35eb9f.png)

**Comment by ethanmoffat** [comment]
Both issues fixed: commits a118821 and b0dbbbb
