### ISSUE TITLE
Inventory item bug 

### ISSUE THREAD

**Issue by Rubes** [ethanmoffat/EndlessClient#22]
If you drag an item outside of the inventory box to the right, the inventory box will show the box of the item inside. (can't describe well, sorry.)

![image](https://cloud.githubusercontent.com/assets/9473264/7603837/f3701acc-f907-11e4-8959-7caa3b571a77.png)

**Comment by ethanmoffat** [comment]
Yeah this has been happening since I made the inventory, I'll take a look when I'm fixing some drag+drop related stuff.

**Comment by Rubes** [comment]
I fixed the issue (temporarily) but I am not on my computer right now so i cant post it. I'll post it here ASAP

**Comment by ethanmoffat** [comment]
Fixed in commit f46621ebd91651388a6a288f383ac3ae14912cbb. Was checking the bounds of the modified x, y coordinates for the background highlight instead of the actual draw area.
