### ISSUE TITLE
Skin melter is broken for clone

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#253]
Using the item causes a copy of your player with the skele race to appear under you. Refreshing makes them disappear but your race is still the same.

edit:

It will show the correct race after a warp!

**Comment by ethanmoffat** [comment]
I'll have to port over the mainclone handling for skin melter into a local etheos build so I can test this - I don't have skin melter on clone :(

**Comment by ethanmoffat** [comment]
This is due to the use of AVATAR_REMOVE and PLAYERS_AGREE, which were assumed to only ever be sent for other characters (not the main character). Updating the packet handlers to handle the main character as well should resolve this.
