### ISSUE TITLE
Map click event triggers when interacting with GUI

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#255]
For example when confirming an item drop amount your player character will walk to where you clicked on the "OK" button

**Comment by ethanmoffat** [comment]
This is a known issue, thought it was a duplicate, but it's a blocker for #225

I need to basically rewrite how the controls library handles input, and redo all input handling for EndlessClient. Right now each Game Component handles input individually. I have a hacky workaround in place, but it's not a clean solution.

The idea right now is to track z-order of the components and send messages to the topmost enabled/visible component.
