### ISSUE TITLE
Double clicking items is weird

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#256]
Seems like I have to try a lot to get it to trigger as a double click

**Comment by ethanmoffat** [comment]
Click+drag in item inventory is pretty messy. The spell click+drag is a lot cleaner - for some reason I wrote it two different ways when I originally implemented it, and ported it from the old code base without thinking too hard about fixing it.

Inventory click+drag should match spell panel click+drag.

**Comment by ethanmoffat** [comment]
XNAControls v2.0 is in progress, should address this.
