### ISSUE TITLE
Relogging results in an invisible player character

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#260]
Any subsequent logins after the first will result in the player character not rendering. F12 and Warping do not fix this.

**Comment by ethanmoffat** [comment]
The renderer for the main character is created when `CharacterRendererUpdater` sees there isn't a main character renderer that matches the state of the main character model. Subsequent logins do not hit this same code path.

Probably could fix this by making sure the `CharacterStateCache` gets cleared on logout
