### ISSUE TITLE
flowie / espring health bars are much too high

### ISSUE THREAD

**Issue by DanDecrypted** [ethanmoffat/EndlessClient#290]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/464887/207387313-f5d0612c-8bf1-4f0f-8408-b061552f2919.png">

yet to confirm if this is a problem in vanilla

**Comment by CoderDanUK** [comment]
Having looked at the code these are centered around the nameplate being in the wrong place.

**Comment by ethanmoffat** [comment]
I tweaked the name label positioning a bit when I updated to bitmap fonts. Unfortunately still haven't been able to make it play nicely with differently sized NPCs. The metadata negative y offset unfortunately isn't working like I expected.
