### ISSUE TITLE
Missing sound effect when giving "safety comment" for dropping a large amount of gold

### ISSUE THREAD

**Issue by ethanmoffat** [ethanmoffat/EndlessClient#319]
In the vanilla client, the sound effect `Login` (also `ServerMessage`) plays when the dialog is shown

**Comment by AstralSkies** [comment]
If I remember correctly, the sound effect is applied once along with the safety message.

**Comment by ethanmoffat** [comment]
You're correct, the dialog/sfx is only shown once
