### ISSUE TITLE
Visual glitch with chairs facing "Up" direction

### ISSUE THREAD

**Issue by ethanmoffat** [ethanmoffat/EndlessClient#335]
Expected
<img width="69" alt="image" src="https://github.com/ethanmoffat/EndlessClient/assets/8301078/678c98ed-8fd1-4a17-b505-3f7241ca1607">

Actual
<img width="108" alt="image" src="https://github.com/ethanmoffat/EndlessClient/assets/8301078/26a7f4e1-ca74-4cf2-a99e-d6882e2f97ac">

**Comment by sorokya** [comment]
Down chairs also look off
![image](https://github.com/ethanmoffat/EndlessClient/assets/3664832/e23daf9a-3e68-4128-8e52-53710e425298)

**Comment by ethanmoffat** [comment]
@sorokya see #334, this one is more about the chair backs not rendering over the sitting player
