### ISSUE TITLE
Rendering gold for example near bank locker

### ISSUE THREAD

**Issue by sjbmcg** [ethanmoffat/EndlessClient#344]
Actual:
![image](https://github.com/ethanmoffat/EndlessClient/assets/70440468/908bc0c8-0411-4636-8c52-6cc17513e6a9)
Expected:
![image](https://github.com/ethanmoffat/EndlessClient/assets/70440468/a56462f8-7251-485a-ad69-f19c751ad8c8)
Replication:
Drop 100,000g near a bank locker

**Comment by ethanmoffat** [comment]
Should be fixed along with #112
