### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by thewayupp** [ethanmoffat/EndlessClient#35]
Whenever i open the client i get
"There was an error initializing the sound manager"

**Comment by ethanmoffat** [comment]
Did you copy the sound files (sfx) to the bin directory?
________________________________

**Comment by thewayupp** [comment]
![image](https://cloud.githubusercontent.com/assets/14032950/9564051/7347be7e-4e5f-11e5-89d0-f64188650e02.png)

**Comment by ethanmoffat** [comment]
Ok but is there anything actually in the SFX folder? If it can't find the sound files that's the error message you're going to see. Did you even look at the [readme file](https://github.com/ethanmoffat/EndlessClient#Download)?

**Comment by thewayupp** [comment]
![image](https://cloud.githubusercontent.com/assets/14032950/9564087/5227a500-4e60-11e5-8596-103dec9557e4.png)
I copied sfx folder from the eozip to the release folder. So yes, all of the sfx is in the folder.

**Comment by thewayupp** [comment]
forgot to copy mfx
topkek

**Comment by ethanmoffat** [comment]
Ahh that would do it. I'm making the error message a little more detailed than it is for future versions.
