### ISSUE TITLE
Changing password

### ISSUE THREAD

**Issue by sjbmcg** [ethanmoffat/EndlessClient#360]
Issue:

![image](https://github.com/ethanmoffat/EndlessClient/assets/70440468/7e9d8aac-a488-4a32-8191-24289efb0ccf)

Altering your current password to a password containing a number logs your character in-game.  For example,

1. Start with your base password (e.g., “golden”).
2. Add a number (e.g., “golden1”)

![image](https://github.com/ethanmoffat/EndlessClient/assets/70440468/6416b4bd-5b5c-4495-8a3d-7b71385f3976)

**Comment by ethanmoffat** [comment]
Ah yes - I'd noticed this too, but forgot to make an issue. Thanks for opening this 👍🏻
