### ISSUE TITLE
.net 8.0

### ISSUE THREAD

**Issue by ethanmoffat** [ethanmoffat/EndlessClient#376]
EOL for .net 6.0 updates is November 2024. Update to next LTS release (.net 8.0) should be completed for EndlessClient and all dependencies. This includes:

- EndlessClient project
- EOLib.* projects
- PELoaderLib
- XNAControls
- eolib-dotnet
    - the project itself is netstandard so should be fine, but the test code is net6.0, so it'd be a good idea to make sure this is up to date as well.

This is highly dependent on MonoGame support for .net 8.0.

**Comment by MrDanOak** [comment]
https://www.reddit.com/r/monogame/comments/18lhtb4/net_8_meet_monogame/
