### ISSUE TITLE
IndexOutOfRangeException, ArrowKeyListener.cs, World.Instance.ActiveMapRenderer.MapRef.TileLookup[destY, destX];

### ISSUE THREAD

**Issue by squiblez** [ethanmoffat/EndlessClient#39]
Started happening after commits a353519-b0ac380, haven't been able to isolate much of the issue aside from that(for me) it happens when using the warp at map 5- x86y47, just leaving Aeven to the Malone Outlet (map 7).

Standing beside the warp for a few seconds to get across maps seems to work, and I tried using a Try-Catch statement to simply skip the issue, but it just crashes the client without an exception.

![screenshot5](https://cloud.githubusercontent.com/assets/14168449/9926881/6d67ab54-5ce7-11e5-956b-8b1eb92bd711.jpg)

**Comment by ethanmoffat** [comment]
Oops.

Fixed in commit 744bd25
